### ISSUE TITLE
cert issue?

### ISSUE THREAD

**Issue by IzzySoft** [Rudloff/hangupsdroid#15]
Your update just arrived at my repo yesterday, and threw an error on `fdroid update`:

```
DOES NOT VERIFY
ERROR: JAR signer MYKEY.DSA: JAR signature META-INF/MYKEY.DSA uses digest algorithm 2.16.840.1.101.3.4.2.1 and signature algorithm 1.2.840.10040.4.1 which is not supported on API Levels [[16, 21]]
ERROR: 
repo/pro.rudloff.hangupsdroid_0.1.1.apk: 
```

It was included nevertheless (I allow for deprecated algos, as the corresponding AntiFeature is automatically added). Just wanted to let you know.

**Comment by Rudloff** [comment]
Thanks for telling me. I think it is because I forgot to use apksigner instead of jarsigner.
If I replace the APK on GitHub, will you be able to use the new one?

**Comment by IzzySoft** [comment]
Sure, just let me know when it's there – as fdroidserver accepted it nevertheless, I need to replace it manually.

**Comment by Rudloff** [comment]
@IzzySoft I replaced the APK, can you try again?

**Comment by IzzySoft** [comment]
Yes, thanks! APKSigner no longer complains. Replaced it; should hopefully show up with the next sync in a few hours.
