### ISSUE TITLE
Support 2FA login

### ISSUE THREAD

**Issue by Rudloff** [Rudloff/hangupsdroid#4]
Maybe wait for https://github.com/tdryer/hangups/issues/429 to be fixed first.

**Comment by Rudloff** [comment]
Fixed in f4f3cfb1e87a091c394c7d5d5b2fc84c01c85531.

**Comment by TPS** [comment]
I'm not sure this is fixed, as I keep getting `GoogleAuthError: Authorization code cookie not found`, both w/ regular  & [app password](https://myaccount.google.com/apppasswords).  Or is it because I'm running a stock Android build?

**Comment by Rudloff** [comment]
It won't work with an app password, you need to use your regular password.
Can you try with [hangups](https://github.com/tdryer/hangups) directly to see if this is an upstream issue?
Only OTP and SMS methods will work.

(Also, if you made several attemps that failed, it is possible that your account now displays a captcha that hangups can't see. This usually last a few hours.)

**Comment by TPS** [comment]
I can't figure out how to get HangUps itself running, so it must be *nix software. 😳  Any idea if there's a Windows binary someplace I can try?

**Comment by Rudloff** [comment]
hangups is a Python app so it should be cross-platform but I have no experience running Python on Windows, sorry :disappointed: 
(The [documentation](https://hangups.readthedocs.io/en/latest/installation.html) recommends using [Cygwin](http://cygwin.com/) but that basically installs an Unix environment in Windows so it might be too much work just to test this one thing.)

**Comment by dracuking** [comment]
Im getting the same error: GoogleAuthError: Authorization code cookie not found. Running a samsung galaxy s9+. Tried on both my data and home wifi network. The yakyak for desktop works on my home desktop wifi. Google Hangout app connects on my phone. No sure what else to do. I have Allow less secure apps: ON on my google account and tried with 2-step verification on and off. :(
