### ISSUE TITLE
GoogleAuthError: Authorization code cookie not found

### ISSUE THREAD

**Issue by dracuking** [Rudloff/hangupsdroid#9]
Searching through other posts with similar error I'm having. It looks like the issues was closed so I created a new issue. First off, thank you for this app. I've been looking for a way to connect to google hangouts without using google apps. Only thing is I keep getting there error while attempting to log-in. **GoogleAuthError: Authorization code cookie not found**.  I got a samsung galaxy s9+. I just reset it so fresh install. I tried connecting with hangupsdroid but got this error on both data and wifi connection. My Google account has 2-step verification, google prompt, and Allow less secure apps turned on. Im able to log into google hangouts on my desktop wifi using yakyak so i don't think its a network issue, Any ideas?

**Comment by Rudloff** [comment]
> My Google account has 2-step verification, google prompt

Phone prompts are not supported by hangups. The only 2FA methods it supports are OTP and SMS.

(I added a note about this in the README: d120f5cdaa892db430ee9e53f6c3cc0e5478f2bd.)

**Comment by dracuking** [comment]
Ok. On my Google account I disabled Phone prompts and left SMS text on for 2FA. Im assuming the sms is when google sends a sms text to my phone with a number code to enter whenever I log into my google account. I then tried hangupsdroid. Still get the same error message. No other message screen pops up on my phone.

I installed Python / Hangups on my windows desktop and launch it. I get the same error message on the command prompt.

**Comment by Rudloff** [comment]
> I installed Python / Hangups on my windows desktop and launch it. I get the same error message on the command prompt.

Then this is an hangups issue and you should report it [here](https://github.com/tdryer/hangups/issues). I can't do anything if login with hangups does not work sorry.

**Comment by dracuking** [comment]
Ok, ty

**Comment by Rudloff** [comment]
Closing this since it is an upstream issue.
Feel free to reopen if hangups fixes it.
